"""baseline schema

Revision ID: d39845be5408
Revises: 
Create Date: 2026-09-01 06:21:17.792425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39845be5408'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dxy', sa.Float(), nullable=False, comment='美元指数 DXY 点位'),
    sa.Column('us10y_yield', sa.Float(), nullable=False, comment='美债10年期收益率 %'),
    sa.Column('real_rate', sa.Float(), nullable=False, comment='实际利率 %（10Y名义 - 盈亏平衡通胀）'),
    sa.Column('inflation_expectation', sa.Float(), nullable=False, comment='通胀预期 %（盈亏平衡）'),
    sa.Column('risk_off', sa.Integer(), nullable=False, comment='避险情绪 0-10（0=贪婪，10=恐慌）'),
    sa.Column('score', sa.Float(), nullable=False, comment='综合机会评分 0-100'),
    sa.Column('window', sa.String(length=16), nullable=False, comment='投资窗口 strong/medium/weak/standby'),
    sa.Column('signal', sa.String(length=16), nullable=False, comment='方向信号 bullish/bearish/neutral'),
    sa.Column('factors_detail', sa.Text(), nullable=False, comment='各因子明细 JSON 字符串'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False, comment='JSON 字符串'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('daily_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='快照日期'),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('close', sa.Float(), nullable=False, comment='最新收盘价'),
    sa.Column('change_pct', sa.Float(), nullable=False, comment='区间涨跌幅 %'),
    sa.Column('high', sa.Float(), nullable=False, comment='区间最高'),
    sa.Column('low', sa.Float(), nullable=False, comment='区间最低'),
    sa.Column('ma20', sa.Float(), nullable=False, comment='MA20'),
    sa.Column('ma40', sa.Float(), nullable=False, comment='MA40'),
    sa.Column('direction', sa.String(length=12), nullable=False, comment='趋势方向 up/down/sideways'),
    sa.Column('tech_index', sa.Float(), nullable=False, comment='技术面指数'),
    sa.Column('macro_index', sa.Float(), nullable=False, comment='宏观参考指数'),
    sa.Column('news_index', sa.Float(), nullable=False, comment='消息面指数（客户评估）'),
    sa.Column('trend_index', sa.Float(), nullable=False, comment='综合趋势评估指数'),
    sa.Column('index_level', sa.String(length=16), nullable=False, comment='指数等级'),
    sa.Column('macro_detail', sa.Text(), nullable=False, comment='宏观 5 因子 JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_snapshots_snapshot_date'), 'daily_snapshots', ['snapshot_date'], unique=True)
    op.create_table('news_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False, comment='打分日期（每日一条）'),
    sa.Column('score', sa.Float(), nullable=False, comment='消息面看多强度 0-100'),
    sa.Column('direction', sa.String(length=12), nullable=False, comment='bullish/bearish/neutral'),
    sa.Column('notes', sa.Text(), nullable=False, comment='客户研判备注（参考投行观点/链接）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_scores_score_date'), 'news_scores', ['score_date'], unique=True)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='预留多用户，当前单用户=1'),
    sa.Column('symbol', sa.String(length=16), nullable=False, comment='品种代码，如 518880'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='品种名称'),
    sa.Column('quantity', sa.Float(), nullable=False, comment='当前持仓数量（份）'),
    sa.Column('avg_cost', sa.Float(), nullable=False, comment='摊薄成本（元/份）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='open/closed'),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False, comment='关联持仓'),
    sa.Column('side', sa.String(length=8), nullable=False, comment='buy 买入 / sell 卖出'),
    sa.Column('quantity', sa.Float(), nullable=False, comment='成交数量（份）'),
    sa.Column('price', sa.Float(), nullable=False, comment='成交价（元/份）'),
    sa.Column('fee', sa.Float(), nullable=False, comment='手续费'),
    sa.Column('traded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='成交时间'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_records_position_id'), 'trade_records', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_records_position_id'), table_name='trade_records')
    op.drop_table('trade_records')
    op.drop_table('positions')
    op.drop_index(op.f('ix_news_scores_score_date'), table_name='news_scores')
    op.drop_table('news_scores')
    op.drop_index(op.f('ix_daily_snapshots_snapshot_date'), table_name='daily_snapshots')
    op.drop_table('daily_snapshots')
    op.drop_table('app_settings')
    op.drop_table('analysis_records')
    # ### end Alembic commands ###
